services:

  postgres:
    image: postgres:17
    container_name: clinic-postgres
    environment:
      POSTGRES_DB: clinic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: clinic-pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@clinic.com
        PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres

volumes:
    postgres_data: